apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "<your-mongo-username>"
  MONGO_INITDB_ROOT_PASSWORD: "<your-mongo-password>"
  MONGO_EXPRESS_URL: "mongodb://<your-mongo-username>:<your-mongo-password>@mongo:27017/"
